### ISSUE TITLE
Windows errors 

### ISSUE THREAD

**Issue by nsk** [richardyc/Chrome-GPT#11]
(chrome-gpt-py3.10) PS C:\Chrome-GPT> python -m chromegpt -v -t "test"
Traceback (most recent call last):
  File "C:\Users\nsk\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\nsk\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Chrome-GPT\chromegpt\__main__.py", line 4, in <module>
    from chromegpt.main import run_chromegpt
  File "C:\Chrome-GPT\chromegpt\main.py", line 3, in <module>
    from chromegpt.agent.zeroshot import BabyAGIAgent, ZeroShotAgent
  File "C:\Chrome-GPT\chromegpt\agent\zeroshot.py", line 49
    verbose=verbose,
IndentationError: unexpected indent

**Comment by nsk** [comment]
idem
