### ISSUE TITLE
ModuleNotFoundError: No module named 'langchain.experimental'

### ISSUE THREAD

**Issue by coder-r** [richardyc/Chrome-GPT#34]
Any idea what I am getting the issue below?

I have installed langchain module many times.

 python3 -m chromegpt --help
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/git/Chrome-GPT/chromegpt/__main__.py", line 4, in <module>
    from chromegpt.main import run_chromegpt
  File "/root/git/Chrome-GPT/chromegpt/main.py", line 1, in <module>
    from chromegpt.agent.autogpt import AutoGPTAgent
  File "/root/git/Chrome-GPT/chromegpt/agent/autogpt/__init__.py", line 2, in <module>
    from .autogpt import AutoGPTAgent  # noqa: F401
  File "/root/git/Chrome-GPT/chromegpt/agent/autogpt/autogpt.py", line 6, in <module>
    from langchain.experimental import AutoGPT
ModuleNotFoundError: No module named 'langchain.experimental'

**Comment by gurutech1416** [comment]
Hey,
Change the code from langchain.experimental to langchain_experimental
