### ISSUE TITLE
raise MaxRetryError

### ISSUE THREAD

**Issue by zorenwin** [richardyc/Chrome-GPT#37]
When I try to run and give a task to Chrome-GPT, I received this error

    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-chrome', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1199345d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

**Comment by xifeng0126** [comment]
I also meet this error. Do you have solved it?

**Comment by BaseInfinity** [comment]
I ran into this as well:
https://github.com/richardyc/Chrome-GPT/issues/40

I reverted my fork back to before the docker changes and upgraded selenium and now it works again, here's the fork if you're curious:
https://github.com/BaseInfinity/SeleniumGPT

**Comment by xifeng0126** [comment]
> I ran into this as well: #40
> 
> I reverted my fork back to before the docker changes and upgraded selenium and now it works again, here's the fork if you're curious: https://github.com/BaseInfinity/SeleniumGPT

Thanks for you suggestion. I clone your code, and run it. It opens Chrome but with the error: `12744:17132:1006/164626.176:ERROR:device_event_log_impl.cc(222)] [16:46:26.176] USB: usb_service_win.cc:415 Could not read device interface GUIDs: 系统找不到指定的文件。 (0x2)
`
I think maybe it because i don't set right version of Chrome deriver in code? The version of my Chrome is 117 ,and I can't find available webdriver. So I rollback it to 114 and fix code like this:  
```
PATH = "C:\\Users\\Xifeng\\Downloads\\chromedriver_win32\\chromedriver.exe"

driver = webdriver.Chrome(PATH)
```
 but it did't work.
 Sorry, this is my first time to use selenium, can you give me more detailed advice? 
In addition, my computer system is win11

**Comment by xifeng0126** [comment]
> > I ran into this as well: #40
> > I reverted my fork back to before the docker changes and upgraded selenium and now it works again, here's the fork if you're curious: https://github.com/BaseInfinity/SeleniumGPT
> 
> Thanks for you suggestion. I clone your code, and run it. It opens Chrome but with the error: `12744:17132:1006/164626.176:ERROR:device_event_log_impl.cc(222)] [16:46:26.176] USB: usb_service_win.cc:415 Could not read device interface GUIDs: 系统找不到指定的文件。 (0x2) ` I think maybe it because i don't set right version of Chrome deriver in code? The version of my Chrome is 117 ,and I can't find available webdriver. So I rollback it to 114 and fix code like this:
> 
> ```
> PATH = "C:\\Users\\Xifeng\\Downloads\\chromedriver_win32\\chromedriver.exe"
> 
> driver = webdriver.Chrome(PATH)
> ```
> 
> but it did't work. Sorry, this is my first time to use selenium, can you give me more detailed advice? In addition, my computer system is win11

Fine, I find solutoin  ： add 
`chrome_options.add_experimental_option("excludeSwitches", ["enable-logging"])`
now , it seems better:
```
(chrome-gpt-py3.11) PS E:\Code\SeleniumGPT> python -m chromegpt -t "Go to BestBuy and Search for a Nintendo Switch and Add it to your Cart. Your Task is Complete after adding to Cart."  
Traceback (most recent call last):
  File "C:\Users\Xifeng\AppData\Local\pypoetry\Cache\virtualenvs\chrome-gpt-XzrLSabp-py3.11\Lib\site-packages\langchain\agents\chat\output_parser.py", line 22, in parse
    response = json.loads(action.strip())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\anaconda3\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\anaconda3\Lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 4 column 2 (char 68)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "E:\Code\SeleniumGPT\chromegpt\__main__.py", line 44, in <module>
    main()
  File "C:\Users\Xifeng\AppData\Local\pypoetry\Cache\virtualenvs\chrome-gpt-XzrLSabp-py3.11\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xifeng\AppData\Local\pypoetry\Cache\virtualenvs\chrome-gpt-XzrLSabp-py3.11\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\Xifeng\AppData\Local\pypoetry\Cache\virtualenvs\chrome-gpt-XzrLSabp-py3.11\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xifeng\AppData\Local\pypoetry\Cache\virtualenvs\chrome-gpt-XzrLSabp-py3.11\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Code\SeleniumGPT\chromegpt\__main__.py", line 33, in main
    return run_chromegpt(
           ^^^^^^^^^^^^^^
  File "E:\Code\SeleniumGPT\chromegpt\main.py", line 27, in run_chromegpt
    return agent_obj.run([task])
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Code\SeleniumGPT\chromegpt\agent\zeroshot.py", line 57, in run
    return self.agent.run(" ".join(tasks))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xifeng\AppData\Local\pypoetry\Cache\virtualenvs\chrome-gpt-XzrLSabp-py3.11\Lib\site-packages\langchain\chains\base.py", line 238, in run
    return self(args[0], callbacks=callbacks)[self.output_keys[0]]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xifeng\AppData\Local\pypoetry\Cache\virtualenvs\chrome-gpt-XzrLSabp-py3.11\Lib\site-packages\langchain\chains\base.py", line 142, in __call__
    raise e
  File "C:\Users\Xifeng\AppData\Local\pypoetry\Cache\virtualenvs\chrome-gpt-XzrLSabp-py3.11\Lib\site-packages\langchain\chains\base.py", line 136, in __call__
    self._call(inputs, run_manager=run_manager)
  File "C:\Users\Xifeng\AppData\Local\pypoetry\Cache\virtualenvs\chrome-gpt-XzrLSabp-py3.11\Lib\site-packages\langchain\agents\agent.py", line 905, in _call
    next_step_output = self._take_next_step(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xifeng\AppData\Local\pypoetry\Cache\virtualenvs\chrome-gpt-XzrLSabp-py3.11\Lib\site-packages\langchain\agents\agent.py", line 749, in _take_next_step
    raise e
  File "C:\Users\Xifeng\AppData\Local\pypoetry\Cache\virtualenvs\chrome-gpt-XzrLSabp-py3.11\Lib\site-packages\langchain\agents\agent.py", line 742, in _take_next_step
    output = self.agent.plan(
             ^^^^^^^^^^^^^^^^
  File "C:\Users\Xifeng\AppData\Local\pypoetry\Cache\virtualenvs\chrome-gpt-XzrLSabp-py3.11\Lib\site-packages\langchain\agents\agent.py", line 426, in plan
    return self.output_parser.parse(full_output)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xifeng\AppData\Local\pypoetry\Cache\virtualenvs\chrome-gpt-XzrLSabp-py3.11\Lib\site-packages\langchain\agents\chat\output_parser.py", line 26, in parse
    raise OutputParserException(f"Could not parse LLM output: {text}")
langchain.schema.OutputParserException: Could not parse LLM output: Question: What should I do?
Thought: I need to open the BestBuy website and search for a Nintendo Switch. Once I find it, I need to add it to my cart.
Action:
```
{
  "action": "goto",
  "action_input": "https://www.bestbuy.com/"
},
{
  "action": "fill_form",
  "action_input": "{\"search\":\"Nintendo Switch\"}"
},
{
  "action": "click",
  "action_input": "//*[@id=\"main-results\"]/div[1]/div/div/div[2]/h4/a"
},
{
  "action": "click",
  "action_input": "//*[@id=\"shop-product-page\"]/main/div[2]/div[1]/div[2]/div[1]/div[3]/div/div[2]/div[1]/button"
}
```
```
But still with error

**Comment by OldHunter0** [comment]
> I ran into this as well: #40
> 
> I reverted my fork back to before the docker changes and upgraded selenium and now it works again, here's the fork if you're curious: https://github.com/BaseInfinity/SeleniumGPT

need to Rolled back changes to eb7cbced
so I think maybe newest commits import this bug.
