### ISSUE TITLE
metaclass conflict

### ISSUE THREAD

**Issue by gurutech1416** [richardyc/Chrome-GPT#39]
Hey Richard, Thanks for the code, but when I try to run it on my Windows Machine then I got the below error. Can you please let me know how can I resolve this. 

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Agent\ChromGPTV2\chromegpt\__main__.py", line 4, in <module>
    from chromegpt.main import run_chromegpt
  File "D:\Agent\ChromGPTV2\chromegpt\main.py", line 1, in <module>
    from chromegpt.agent.autogpt import AutoGPTAgent
  File "D:\Agent\ChromGPTV2\chromegpt\agent\autogpt\__init__.py", line 2, in <module>
    from .autogpt import AutoGPTAgent  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Agent\ChromGPTV2\chromegpt\agent\autogpt\autogpt.py", line 16, in <module>
    from chromegpt.agent.autogpt.prompt import AutoGPTPrompt
  File "D:\Agent\ChromGPTV2\chromegpt\agent\autogpt\prompt.py", line 16, in <module>
    class AutoGPTPrompt(BaseChatPromptTemplate, BaseModel):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

If any other folk can help me, then it will be great. Thanks

**Comment by yangcurve** [comment]
same
