### ISSUE TITLE
ModuleNotFoundError: No module named 'langchain.experimental'

### ISSUE THREAD

**Issue by endintro** [richardyc/Chrome-GPT#8]
After installing and executing all the setups in Windows 11 PowerShell command line, the following error occurred.

`PS C:\Users\Jun\code\Chrome-GPT> python -m chromegpt
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Jun\code\Chrome-GPT\chromegpt\__main__.py", line 4, in <module>
    from chromegpt.main import run_chromegpt
  File "C:\Users\Jun\code\Chrome-GPT\chromegpt\main.py", line 1, in <module>
    from chromegpt.agent.autogpt import AutoGPTAgent
  File "C:\Users\Jun\code\Chrome-GPT\chromegpt\agent\autogpt\__init__.py", line 2, in <module>
    from .autogpt import AutoGPTAgent  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jun\code\Chrome-GPT\chromegpt\agent\autogpt\autogpt.py", line 6, in <module>
    from langchain.experimental import AutoGPT
ModuleNotFoundError: No module named 'langchain.experimental'`

What else needs to be configured? Thank you.

**Comment by piyush101** [comment]
Run 

`poetry install`

**Comment by caocao4856** [comment]
This commond is not working. Can you please assist in resolving the issue?

**Comment by ykn0309** [comment]
run
`poety shell`
